config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root "my_ranks#index"

  resources :my_ranks do 
    put :sort
    post :hold_contents
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/my_rank.rb
class MyRank < ApplicationRecord
  include RankedModel 
  ranks :row_order , with_same: :user_id 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/my_ranks_controller.rb
class MyRanksController < ApplicationController

  def index
    # TOD：ユーザーIDを仮で1に設定、devceを導入する
    @myRank = MyRank.where(user_id: 1).rank(:row_order)
  end

  def new
    @myRank = MyRank.new
  end

  def create
    MyRank.create(my_rank_params)
    redirect_to my_ranks_path
  end

  def update
    myRank = MyRank.find(params[:id])
    myRank.update(my_rank_params)
    redirect_to my_ranks_path
  end

  def sort
    myRank = MyRank.find(params[:my_rank_id])
    myRank.update(my_rank_params)
  end

  private
  def my_rank_params
    params.require(:my_rank).permit(:title, :contents, :row_order_position).merge(user_id: 1)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/my_ranks_helper.rb
module MyRanksHelper
end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title MyRanking
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = yield

app/views/my_ranks/index.html.haml
%p#notice= notice
%h1 マイランキング
%table.table.table-hover.w-50
  %thead
    %tr
      %th 
        タイトル
      %th 
        感想
      %th 
        表示
      %th 
        編集
      %th 
        削除
      %th
        保留
  %tbody.table-sortable
    - @myRank.where(hold:0).each do |myrank|
      %tr.item{"data-model-name": myrank.class.name.underscore, "data-update-url": my_rank_sort_path(myrank)}
        %td
          = myrank.title
        %td
          = myrank.contents
        %td
          = link_to 'Show', '#'
        %td
          = link_to 'Edit', '#'
        %td
          = link_to 'Destroy', myrank, method: :delete, data: { confirm: 'Are you sure?' }
        %td
          .review_my_count_area
            = link_to my_rank_hold_contents_path(myrank), method: :post, remote: :true, class: :like_review_btn do
              .like_review_link
                .like_review
                  test

%br
%br

%table.table.table-hover.w-50
  %thead
    %tr
      %th 
        タイトル
      %th 
        感想
      %th 
        表示
      %th 
        編集
      %th 
        削除
      %th
        保留
  %tbody.table-sortable
    - @myRank.where(hold:1).each do |myrank|
      %tr.item{"data-model-name": myrank.class.name.underscore, "data-update-url": my_rank_sort_path(myrank)}
        %td
          = myrank.title
        %td
          = myrank.contents
        %td
          = link_to 'Show', '#'
        %td
          = link_to 'Edit', '#'
        %td
          = link_to 'Destroy', myrank, method: :delete, data: { confirm: 'Are you sure?' }
        %td
          .review_my_count_area
            = link_to my_rank_hold_contents_path(myrank), method: :post, remote: :true, class: :like_review_btn do
              .like_review_link
                .like_review
                  test

%br/
= link_to '新規登録', new_my_rank_path

app/views/my_ranks/new.html.haml
%p#notice= notice
%h1 マイランキング
= form_with model:@myRank, local:true do |f|
  .mb-3
    %label.form-label
      タイトル
    = f.text_field :title, class:"form-control"
  .mb-3
    %label.form-label 
      感想
    = f.text_field :contents, class:"form-control"
  = f.submit "登録する" ,class:"btn btn-primary"